version: '3'

services:
  redis:
    container_name: redis
    hostname: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    image: redis:alpine
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  redis-manager:
    container_name: redis-manager
    restart: always
    image: redislabs/redisinsight:latest
    ports:
      - ${REDIS_MANAGER_PORT}:${REDIS_MANAGER_PORT}

  pgsql:
    image: postgres:alpine
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    container_name: pgsql
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/app
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  pgsql-sonar:
    image: postgres:alpine
    ports:
      - ${SONAR_DATABASE_PORT}:${SONAR_DATABASE_PORT}
    container_name: pgsql-sonar
    restart: always
    volumes:
      - sonarqube_db:/var/lib/postgresql/sonar
    environment:
      POSTGRES_USER: ${SONAR_DATABASE_USER}
      POSTGRES_PASSWORD: ${SONAR_DATABASE_PASSWORD}
      POSTGRES_DB: ${SONAR_DATABASE_NAME}

  pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: always
        environment: 
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports: 
            - ${PGADMIN_PORT}
        depends_on: 
            - pgsql    

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    restart: always
    environment:
      SONARQUBE_JDBC_USERNAME: ${SONAR_DATABASE_USER}
      SONARQUBE_JDBC_PASSWORD: ${SONAR_DATABASE_PASSWORD}
      SONARQUBE_JDBC_URL: jdbc:postgresql://pgsql-sonar:5432/${SONAR_DATABASE_NAME}
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

volumes:
  sonarqube_bundled-plugins:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_db:
  pg-data-sonar:
  pg-data:
