version: '3.8'

services:
  app:
    container_name: openfinance
    image: node:alpine
    build:
      context: .
      target: openfinance
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: yarn test:e2e
    networks:
      - webnet
    depends_on:
      - redis-test
      - postgres-test

  redis-test:
    container_name: redis-test
    hostname: redis-test
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    image: redis:alpine
    ports:
      - '6380:6380'
    networks:
      - webnet

  postgres-test:
    container_name: postgres-test
    image: postgres:14
    ports:
      - '5433:5432'
    networks:
      - webnet
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  webnet:

volumes:
  pgdata:
  logs: