export type AppProperties = {
    DATABASE_HOST: string;
    DATABASE_PORT: string;
    DATABASE_USER: string;
    DATABASE_PASSWORD: string;
    DATABASE_NAME: string;
    DATABASE_SCHEMA: string;
    DATABASE_SYNCHRONIZE: string;
    PASSWORD_ENCRYPTION_KEY: string;
    PASSWORD_ENCRYPTION_ALGORITHM: string;
    PASSWORD_ENCRYPTION_LENGTH: number;
    PASSWORD_ENCRYPTION_IV: string;
    REDIS_HOST: string;
    REDIS_PORT: number;
    REDIS_PASSWORD: string;
    JWT_SECRET: string;
    JWT_EXPIRATION_TIME: number;
    JWT_REFRESH_TOKEN_EXPIRATION_TIME: number;
    ENCRYPTION_PASSWORD: string;
    ENCRYPTION_IV: string;
};
